'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SissaCashflowService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransaccionEntityObject", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransaccionEntityObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AcreditadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCajaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCajeroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSucursalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DivisaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EsEfectivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FolioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraFinField As System.TimeSpan
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraInicioField As System.TimeSpan
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCajaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCorteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdRetiroField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTransaccionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteOtrosField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteOtrosDField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteTotalField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MovimientosField As System.Collections.Generic.List(Of SissaCashflowService.TransaccionDetailEntityObject)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroCuentaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroEnvaseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroRemisionField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As Char
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoCambioField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalMXNField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalUSDField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalUSDConvertField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioRegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rowIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Acreditado() As Boolean
            Get
                Return Me.AcreditadoField
            End Get
            Set
                If (Me.AcreditadoField.Equals(value) <> true) Then
                    Me.AcreditadoField = value
                    Me.RaisePropertyChanged("Acreditado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCaja() As String
            Get
                Return Me.ClaveCajaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCajaField, value) <> true) Then
                    Me.ClaveCajaField = value
                    Me.RaisePropertyChanged("ClaveCaja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCajero() As String
            Get
                Return Me.ClaveCajeroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCajeroField, value) <> true) Then
                    Me.ClaveCajeroField = value
                    Me.RaisePropertyChanged("ClaveCajero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCliente() As String
            Get
                Return Me.ClaveClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveClienteField, value) <> true) Then
                    Me.ClaveClienteField = value
                    Me.RaisePropertyChanged("ClaveCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSucursal() As String
            Get
                Return Me.ClaveSucursalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSucursalField, value) <> true) Then
                    Me.ClaveSucursalField = value
                    Me.RaisePropertyChanged("ClaveSucursal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Divisa() As String
            Get
                Return Me.DivisaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DivisaField, value) <> true) Then
                    Me.DivisaField = value
                    Me.RaisePropertyChanged("Divisa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EsEfectivo() As Boolean
            Get
                Return Me.EsEfectivoField
            End Get
            Set
                If (Me.EsEfectivoField.Equals(value) <> true) Then
                    Me.EsEfectivoField = value
                    Me.RaisePropertyChanged("EsEfectivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Folio() As String
            Get
                Return Me.FolioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FolioField, value) <> true) Then
                    Me.FolioField = value
                    Me.RaisePropertyChanged("Folio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraFin() As System.TimeSpan
            Get
                Return Me.HoraFinField
            End Get
            Set
                If (Me.HoraFinField.Equals(value) <> true) Then
                    Me.HoraFinField = value
                    Me.RaisePropertyChanged("HoraFin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraInicio() As System.TimeSpan
            Get
                Return Me.HoraInicioField
            End Get
            Set
                If (Me.HoraInicioField.Equals(value) <> true) Then
                    Me.HoraInicioField = value
                    Me.RaisePropertyChanged("HoraInicio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCaja() As Integer
            Get
                Return Me.IdCajaField
            End Get
            Set
                If (Me.IdCajaField.Equals(value) <> true) Then
                    Me.IdCajaField = value
                    Me.RaisePropertyChanged("IdCaja")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCorte() As Integer
            Get
                Return Me.IdCorteField
            End Get
            Set
                If (Me.IdCorteField.Equals(value) <> true) Then
                    Me.IdCorteField = value
                    Me.RaisePropertyChanged("IdCorte")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdRetiro() As Integer
            Get
                Return Me.IdRetiroField
            End Get
            Set
                If (Me.IdRetiroField.Equals(value) <> true) Then
                    Me.IdRetiroField = value
                    Me.RaisePropertyChanged("IdRetiro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTransaccion() As Integer
            Get
                Return Me.IdTransaccionField
            End Get
            Set
                If (Me.IdTransaccionField.Equals(value) <> true) Then
                    Me.IdTransaccionField = value
                    Me.RaisePropertyChanged("IdTransaccion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImporteOtros() As Decimal
            Get
                Return Me.ImporteOtrosField
            End Get
            Set
                If (Me.ImporteOtrosField.Equals(value) <> true) Then
                    Me.ImporteOtrosField = value
                    Me.RaisePropertyChanged("ImporteOtros")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImporteOtrosD() As Decimal
            Get
                Return Me.ImporteOtrosDField
            End Get
            Set
                If (Me.ImporteOtrosDField.Equals(value) <> true) Then
                    Me.ImporteOtrosDField = value
                    Me.RaisePropertyChanged("ImporteOtrosD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImporteTotal() As Decimal
            Get
                Return Me.ImporteTotalField
            End Get
            Set
                If (Me.ImporteTotalField.Equals(value) <> true) Then
                    Me.ImporteTotalField = value
                    Me.RaisePropertyChanged("ImporteTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Movimientos() As System.Collections.Generic.List(Of SissaCashflowService.TransaccionDetailEntityObject)
            Get
                Return Me.MovimientosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MovimientosField, value) <> true) Then
                    Me.MovimientosField = value
                    Me.RaisePropertyChanged("Movimientos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroCuenta() As String
            Get
                Return Me.NumeroCuentaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroCuentaField, value) <> true) Then
                    Me.NumeroCuentaField = value
                    Me.RaisePropertyChanged("NumeroCuenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroEnvase() As String
            Get
                Return Me.NumeroEnvaseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroEnvaseField, value) <> true) Then
                    Me.NumeroEnvaseField = value
                    Me.RaisePropertyChanged("NumeroEnvase")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroRemision() As Double
            Get
                Return Me.NumeroRemisionField
            End Get
            Set
                If (Me.NumeroRemisionField.Equals(value) <> true) Then
                    Me.NumeroRemisionField = value
                    Me.RaisePropertyChanged("NumeroRemision")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observaciones() As String
            Get
                Return Me.ObservacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionesField, value) <> true) Then
                    Me.ObservacionesField = value
                    Me.RaisePropertyChanged("Observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Referencia() As String
            Get
                Return Me.ReferenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenciaField, value) <> true) Then
                    Me.ReferenciaField = value
                    Me.RaisePropertyChanged("Referencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As Char
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tipo() As Integer
            Get
                Return Me.TipoField
            End Get
            Set
                If (Me.TipoField.Equals(value) <> true) Then
                    Me.TipoField = value
                    Me.RaisePropertyChanged("Tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoCambio() As Decimal
            Get
                Return Me.TipoCambioField
            End Get
            Set
                If (Me.TipoCambioField.Equals(value) <> true) Then
                    Me.TipoCambioField = value
                    Me.RaisePropertyChanged("TipoCambio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalMXN() As Decimal
            Get
                Return Me.TotalMXNField
            End Get
            Set
                If (Me.TotalMXNField.Equals(value) <> true) Then
                    Me.TotalMXNField = value
                    Me.RaisePropertyChanged("TotalMXN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalUSD() As Decimal
            Get
                Return Me.TotalUSDField
            End Get
            Set
                If (Me.TotalUSDField.Equals(value) <> true) Then
                    Me.TotalUSDField = value
                    Me.RaisePropertyChanged("TotalUSD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalUSDConvert() As Decimal
            Get
                Return Me.TotalUSDConvertField
            End Get
            Set
                If (Me.TotalUSDConvertField.Equals(value) <> true) Then
                    Me.TotalUSDConvertField = value
                    Me.RaisePropertyChanged("TotalUSDConvert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UsuarioRegistro() As String
            Get
                Return Me.UsuarioRegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioRegistroField, value) <> true) Then
                    Me.UsuarioRegistroField = value
                    Me.RaisePropertyChanged("UsuarioRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rowID() As String
            Get
                Return Me.rowIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.rowIDField, value) <> true) Then
                    Me.rowIDField = value
                    Me.RaisePropertyChanged("rowID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransaccionDetailEntityObject", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransaccionDetailEntityObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CantidadPiezasField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveDenominacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveMonedaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSucursalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DenominacionField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdTransaccionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroValidadorField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SerieCaseteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SerieValidadorField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CantidadPiezas() As Integer
            Get
                Return Me.CantidadPiezasField
            End Get
            Set
                If (Me.CantidadPiezasField.Equals(value) <> true) Then
                    Me.CantidadPiezasField = value
                    Me.RaisePropertyChanged("CantidadPiezas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveDenominacion() As String
            Get
                Return Me.ClaveDenominacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveDenominacionField, value) <> true) Then
                    Me.ClaveDenominacionField = value
                    Me.RaisePropertyChanged("ClaveDenominacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveMoneda() As String
            Get
                Return Me.ClaveMonedaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveMonedaField, value) <> true) Then
                    Me.ClaveMonedaField = value
                    Me.RaisePropertyChanged("ClaveMoneda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSucursal() As String
            Get
                Return Me.ClaveSucursalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSucursalField, value) <> true) Then
                    Me.ClaveSucursalField = value
                    Me.RaisePropertyChanged("ClaveSucursal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Denominacion() As Decimal
            Get
                Return Me.DenominacionField
            End Get
            Set
                If (Me.DenominacionField.Equals(value) <> true) Then
                    Me.DenominacionField = value
                    Me.RaisePropertyChanged("Denominacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdTransaccion() As Integer
            Get
                Return Me.IdTransaccionField
            End Get
            Set
                If (Me.IdTransaccionField.Equals(value) <> true) Then
                    Me.IdTransaccionField = value
                    Me.RaisePropertyChanged("IdTransaccion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Importe() As Decimal
            Get
                Return Me.ImporteField
            End Get
            Set
                If (Me.ImporteField.Equals(value) <> true) Then
                    Me.ImporteField = value
                    Me.RaisePropertyChanged("Importe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroValidador() As Integer
            Get
                Return Me.NumeroValidadorField
            End Get
            Set
                If (Me.NumeroValidadorField.Equals(value) <> true) Then
                    Me.NumeroValidadorField = value
                    Me.RaisePropertyChanged("NumeroValidador")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SerieCasete() As String
            Get
                Return Me.SerieCaseteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SerieCaseteField, value) <> true) Then
                    Me.SerieCaseteField = value
                    Me.RaisePropertyChanged("SerieCasete")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SerieValidador() As String
            Get
                Return Me.SerieValidadorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SerieValidadorField, value) <> true) Then
                    Me.SerieValidadorField = value
                    Me.RaisePropertyChanged("SerieValidador")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransaccionResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransaccionResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HasErrorField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RowIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HasError() As Boolean
            Get
                Return Me.HasErrorField
            End Get
            Set
                If (Me.HasErrorField.Equals(value) <> true) Then
                    Me.HasErrorField = value
                    Me.RaisePropertyChanged("HasError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResultMessage() As String
            Get
                Return Me.ResultMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultMessageField, value) <> true) Then
                    Me.ResultMessageField = value
                    Me.RaisePropertyChanged("ResultMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RowID() As String
            Get
                Return Me.RowIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RowIDField, value) <> true) Then
                    Me.RowIDField = value
                    Me.RaisePropertyChanged("RowID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransaccionLogEntity", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransaccionLogEntity
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveSucursalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCajeroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdLogDescripcionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPantallaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdUsuarioField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveSucursal() As String
            Get
                Return Me.ClaveSucursalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveSucursalField, value) <> true) Then
                    Me.ClaveSucursalField = value
                    Me.RaisePropertyChanged("ClaveSucursal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Hora() As String
            Get
                Return Me.HoraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HoraField, value) <> true) Then
                    Me.HoraField = value
                    Me.RaisePropertyChanged("Hora")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCajero() As String
            Get
                Return Me.IdCajeroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdCajeroField, value) <> true) Then
                    Me.IdCajeroField = value
                    Me.RaisePropertyChanged("IdCajero")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdLogDescripcion() As Integer
            Get
                Return Me.IdLogDescripcionField
            End Get
            Set
                If (Me.IdLogDescripcionField.Equals(value) <> true) Then
                    Me.IdLogDescripcionField = value
                    Me.RaisePropertyChanged("IdLogDescripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPantalla() As Integer
            Get
                Return Me.IdPantallaField
            End Get
            Set
                If (Me.IdPantallaField.Equals(value) <> true) Then
                    Me.IdPantallaField = value
                    Me.RaisePropertyChanged("IdPantalla")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdUsuario() As Integer
            Get
                Return Me.IdUsuarioField
            End Get
            Set
                If (Me.IdUsuarioField.Equals(value) <> true) Then
                    Me.IdUsuarioField = value
                    Me.RaisePropertyChanged("IdUsuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eArchivo", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class eArchivo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContenidoChequeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContenidoDepositoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdArchivoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreArchivoChequeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreArchivoDepositoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ContenidoCheque() As String
            Get
                Return Me.ContenidoChequeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContenidoChequeField, value) <> true) Then
                    Me.ContenidoChequeField = value
                    Me.RaisePropertyChanged("ContenidoCheque")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ContenidoDeposito() As String
            Get
                Return Me.ContenidoDepositoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContenidoDepositoField, value) <> true) Then
                    Me.ContenidoDepositoField = value
                    Me.RaisePropertyChanged("ContenidoDeposito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdArchivo() As Integer
            Get
                Return Me.IdArchivoField
            End Get
            Set
                If (Me.IdArchivoField.Equals(value) <> true) Then
                    Me.IdArchivoField = value
                    Me.RaisePropertyChanged("IdArchivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreArchivoCheque() As String
            Get
                Return Me.NombreArchivoChequeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreArchivoChequeField, value) <> true) Then
                    Me.NombreArchivoChequeField = value
                    Me.RaisePropertyChanged("NombreArchivoCheque")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreArchivoDeposito() As String
            Get
                Return Me.NombreArchivoDepositoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreArchivoDepositoField, value) <> true) Then
                    Me.NombreArchivoDepositoField = value
                    Me.RaisePropertyChanged("NombreArchivoDeposito")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FileTransferResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/Cashflow.Web.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FileTransferResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdArchivoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultMessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.FechaField
            End Get
            Set
                If (Me.FechaField.Equals(value) <> true) Then
                    Me.FechaField = value
                    Me.RaisePropertyChanged("Fecha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdArchivo() As Integer
            Get
                Return Me.IdArchivoField
            End Get
            Set
                If (Me.IdArchivoField.Equals(value) <> true) Then
                    Me.IdArchivoField = value
                    Me.RaisePropertyChanged("IdArchivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResultCode() As String
            Get
                Return Me.ResultCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultCodeField, value) <> true) Then
                    Me.ResultCodeField = value
                    Me.RaisePropertyChanged("ResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResultMessage() As String
            Get
                Return Me.ResultMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultMessageField, value) <> true) Then
                    Me.ResultMessageField = value
                    Me.RaisePropertyChanged("ResultMessage")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SissaCashflowService.ICashflowService")>  _
    Public Interface ICashflowService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/TestConnection", ReplyAction:="http://tempuri.org/ICashflowService/TestConnectionResponse")>  _
        Function TestConnection() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/TestConnection", ReplyAction:="http://tempuri.org/ICashflowService/TestConnectionResponse")>  _
        Function TestConnectionAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/InsertTransaccionDeposito", ReplyAction:="http://tempuri.org/ICashflowService/InsertTransaccionDepositoResponse")>  _
        Function InsertTransaccionDeposito(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As SissaCashflowService.TransaccionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/InsertTransaccionDeposito", ReplyAction:="http://tempuri.org/ICashflowService/InsertTransaccionDepositoResponse")>  _
        Function InsertTransaccionDepositoAsync(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/InsertTransaccionRetiro", ReplyAction:="http://tempuri.org/ICashflowService/InsertTransaccionRetiroResponse")>  _
        Function InsertTransaccionRetiro(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As SissaCashflowService.TransaccionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/InsertTransaccionRetiro", ReplyAction:="http://tempuri.org/ICashflowService/InsertTransaccionRetiroResponse")>  _
        Function InsertTransaccionRetiroAsync(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/UpdateDepositoReferenciaStatus", ReplyAction:="http://tempuri.org/ICashflowService/UpdateDepositoReferenciaStatusResponse")>  _
        Function UpdateDepositoReferenciaStatus(ByVal RFC As String, ByVal Depositos As System.Collections.Generic.List(Of SissaCashflowService.TransaccionEntityObject)) As SissaCashflowService.TransaccionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/UpdateDepositoReferenciaStatus", ReplyAction:="http://tempuri.org/ICashflowService/UpdateDepositoReferenciaStatusResponse")>  _
        Function UpdateDepositoReferenciaStatusAsync(ByVal RFC As String, ByVal Depositos As System.Collections.Generic.List(Of SissaCashflowService.TransaccionEntityObject)) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/AddTransactionLog", ReplyAction:="http://tempuri.org/ICashflowService/AddTransactionLogResponse")>  _
        Function AddTransactionLog(ByVal RFC As String, ByVal LogIngo As SissaCashflowService.TransaccionLogEntity) As SissaCashflowService.TransaccionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/AddTransactionLog", ReplyAction:="http://tempuri.org/ICashflowService/AddTransactionLogResponse")>  _
        Function AddTransactionLogAsync(ByVal RFC As String, ByVal LogIngo As SissaCashflowService.TransaccionLogEntity) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/GetFileTransferAcreditaciones", ReplyAction:="http://tempuri.org/ICashflowService/GetFileTransferAcreditacionesResponse")>  _
        Function GetFileTransferAcreditaciones(ByVal Fecha As Date) As SissaCashflowService.eArchivo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/GetFileTransferAcreditaciones", ReplyAction:="http://tempuri.org/ICashflowService/GetFileTransferAcreditacionesResponse")>  _
        Function GetFileTransferAcreditacionesAsync(ByVal Fecha As Date) As System.Threading.Tasks.Task(Of SissaCashflowService.eArchivo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/SendFileTransferResponse", ReplyAction:="http://tempuri.org/ICashflowService/SendFileTransferResponseResponse")>  _
        Function SendFileTransferResponse(ByVal Response As SissaCashflowService.FileTransferResponse) As SissaCashflowService.FileTransferResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/SendFileTransferResponse", ReplyAction:="http://tempuri.org/ICashflowService/SendFileTransferResponseResponse")>  _
        Function SendFileTransferResponseAsync(ByVal Response As SissaCashflowService.FileTransferResponse) As System.Threading.Tasks.Task(Of SissaCashflowService.FileTransferResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/SendFileTransferRecolecciones", ReplyAction:="http://tempuri.org/ICashflowService/SendFileTransferRecoleccionesResponse")>  _
        Function SendFileTransferRecolecciones(ByVal ArchivoInfo As SissaCashflowService.eArchivo) As SissaCashflowService.FileTransferResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICashflowService/SendFileTransferRecolecciones", ReplyAction:="http://tempuri.org/ICashflowService/SendFileTransferRecoleccionesResponse")>  _
        Function SendFileTransferRecoleccionesAsync(ByVal ArchivoInfo As SissaCashflowService.eArchivo) As System.Threading.Tasks.Task(Of SissaCashflowService.FileTransferResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICashflowServiceChannel
        Inherits SissaCashflowService.ICashflowService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CashflowServiceClient
        Inherits System.ServiceModel.ClientBase(Of SissaCashflowService.ICashflowService)
        Implements SissaCashflowService.ICashflowService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TestConnection() As String Implements SissaCashflowService.ICashflowService.TestConnection
            Return MyBase.Channel.TestConnection
        End Function
        
        Public Function TestConnectionAsync() As System.Threading.Tasks.Task(Of String) Implements SissaCashflowService.ICashflowService.TestConnectionAsync
            Return MyBase.Channel.TestConnectionAsync
        End Function
        
        Public Function InsertTransaccionDeposito(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As SissaCashflowService.TransaccionResponse Implements SissaCashflowService.ICashflowService.InsertTransaccionDeposito
            Return MyBase.Channel.InsertTransaccionDeposito(RFC, TransaccionInfo)
        End Function
        
        Public Function InsertTransaccionDepositoAsync(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse) Implements SissaCashflowService.ICashflowService.InsertTransaccionDepositoAsync
            Return MyBase.Channel.InsertTransaccionDepositoAsync(RFC, TransaccionInfo)
        End Function
        
        Public Function InsertTransaccionRetiro(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As SissaCashflowService.TransaccionResponse Implements SissaCashflowService.ICashflowService.InsertTransaccionRetiro
            Return MyBase.Channel.InsertTransaccionRetiro(RFC, TransaccionInfo)
        End Function
        
        Public Function InsertTransaccionRetiroAsync(ByVal RFC As String, ByVal TransaccionInfo As SissaCashflowService.TransaccionEntityObject) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse) Implements SissaCashflowService.ICashflowService.InsertTransaccionRetiroAsync
            Return MyBase.Channel.InsertTransaccionRetiroAsync(RFC, TransaccionInfo)
        End Function
        
        Public Function UpdateDepositoReferenciaStatus(ByVal RFC As String, ByVal Depositos As System.Collections.Generic.List(Of SissaCashflowService.TransaccionEntityObject)) As SissaCashflowService.TransaccionResponse Implements SissaCashflowService.ICashflowService.UpdateDepositoReferenciaStatus
            Return MyBase.Channel.UpdateDepositoReferenciaStatus(RFC, Depositos)
        End Function
        
        Public Function UpdateDepositoReferenciaStatusAsync(ByVal RFC As String, ByVal Depositos As System.Collections.Generic.List(Of SissaCashflowService.TransaccionEntityObject)) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse) Implements SissaCashflowService.ICashflowService.UpdateDepositoReferenciaStatusAsync
            Return MyBase.Channel.UpdateDepositoReferenciaStatusAsync(RFC, Depositos)
        End Function
        
        Public Function AddTransactionLog(ByVal RFC As String, ByVal LogIngo As SissaCashflowService.TransaccionLogEntity) As SissaCashflowService.TransaccionResponse Implements SissaCashflowService.ICashflowService.AddTransactionLog
            Return MyBase.Channel.AddTransactionLog(RFC, LogIngo)
        End Function
        
        Public Function AddTransactionLogAsync(ByVal RFC As String, ByVal LogIngo As SissaCashflowService.TransaccionLogEntity) As System.Threading.Tasks.Task(Of SissaCashflowService.TransaccionResponse) Implements SissaCashflowService.ICashflowService.AddTransactionLogAsync
            Return MyBase.Channel.AddTransactionLogAsync(RFC, LogIngo)
        End Function
        
        Public Function GetFileTransferAcreditaciones(ByVal Fecha As Date) As SissaCashflowService.eArchivo Implements SissaCashflowService.ICashflowService.GetFileTransferAcreditaciones
            Return MyBase.Channel.GetFileTransferAcreditaciones(Fecha)
        End Function
        
        Public Function GetFileTransferAcreditacionesAsync(ByVal Fecha As Date) As System.Threading.Tasks.Task(Of SissaCashflowService.eArchivo) Implements SissaCashflowService.ICashflowService.GetFileTransferAcreditacionesAsync
            Return MyBase.Channel.GetFileTransferAcreditacionesAsync(Fecha)
        End Function
        
        Public Function SendFileTransferResponse(ByVal Response As SissaCashflowService.FileTransferResponse) As SissaCashflowService.FileTransferResponse Implements SissaCashflowService.ICashflowService.SendFileTransferResponse
            Return MyBase.Channel.SendFileTransferResponse(Response)
        End Function
        
        Public Function SendFileTransferResponseAsync(ByVal Response As SissaCashflowService.FileTransferResponse) As System.Threading.Tasks.Task(Of SissaCashflowService.FileTransferResponse) Implements SissaCashflowService.ICashflowService.SendFileTransferResponseAsync
            Return MyBase.Channel.SendFileTransferResponseAsync(Response)
        End Function
        
        Public Function SendFileTransferRecolecciones(ByVal ArchivoInfo As SissaCashflowService.eArchivo) As SissaCashflowService.FileTransferResponse Implements SissaCashflowService.ICashflowService.SendFileTransferRecolecciones
            Return MyBase.Channel.SendFileTransferRecolecciones(ArchivoInfo)
        End Function
        
        Public Function SendFileTransferRecoleccionesAsync(ByVal ArchivoInfo As SissaCashflowService.eArchivo) As System.Threading.Tasks.Task(Of SissaCashflowService.FileTransferResponse) Implements SissaCashflowService.ICashflowService.SendFileTransferRecoleccionesAsync
            Return MyBase.Channel.SendFileTransferRecoleccionesAsync(ArchivoInfo)
        End Function
    End Class
End Namespace
