'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsRemision
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsRemision.WsCashFlowSoap")>  _
    Public Interface WsCashFlowSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Deposito_Consulta", ReplyAction:="*")>  _
        Function Deposito_Consulta(ByVal request As WsRemision.Deposito_ConsultaRequest) As WsRemision.Deposito_ConsultaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Deposito_Consulta", ReplyAction:="*")>  _
        Function Deposito_ConsultaAsync(ByVal request As WsRemision.Deposito_ConsultaRequest) As System.Threading.Tasks.Task(Of WsRemision.Deposito_ConsultaResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Depos", ReplyAction:="*")>  _
        Function Depos(ByVal request As WsRemision.DeposRequest) As WsRemision.DeposResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Depos", ReplyAction:="*")>  _
        Function DeposAsync(ByVal request As WsRemision.DeposRequest) As System.Threading.Tasks.Task(Of WsRemision.DeposResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_punto", ReplyAction:="*")>  _
        Function Obtener_punto(ByVal request As WsRemision.Obtener_puntoRequest) As WsRemision.Obtener_puntoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_punto", ReplyAction:="*")>  _
        Function Obtener_puntoAsync(ByVal request As WsRemision.Obtener_puntoRequest) As System.Threading.Tasks.Task(Of WsRemision.Obtener_puntoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_Remision", ReplyAction:="*")>  _
        Function Obtener_Remision(ByVal request As WsRemision.Obtener_RemisionRequest) As WsRemision.Obtener_RemisionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_Remision", ReplyAction:="*")>  _
        Function Obtener_RemisionAsync(ByVal request As WsRemision.Obtener_RemisionRequest) As System.Threading.Tasks.Task(Of WsRemision.Obtener_RemisionResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetData", ReplyAction:="*")>  _
        Function SetData(ByVal request As WsRemision.SetDataRequest) As WsRemision.SetDataResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetData", ReplyAction:="*")>  _
        Function SetDataAsync(ByVal request As WsRemision.SetDataRequest) As System.Threading.Tasks.Task(Of WsRemision.SetDataResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Guardar_Ticket", ReplyAction:="*")>  _
        Function Guardar_Ticket(ByVal request As WsRemision.Guardar_TicketRequest) As WsRemision.Guardar_TicketResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Guardar_Ticket", ReplyAction:="*")>  _
        Function Guardar_TicketAsync(ByVal request As WsRemision.Guardar_TicketRequest) As System.Threading.Tasks.Task(Of WsRemision.Guardar_TicketResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Sucursales_RFC", ReplyAction:="*")>  _
        Function Consultar_Sucursales_RFC(ByVal request As WsRemision.Consultar_Sucursales_RFCRequest) As WsRemision.Consultar_Sucursales_RFCResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Sucursales_RFC", ReplyAction:="*")>  _
        Function Consultar_Sucursales_RFCAsync(ByVal request As WsRemision.Consultar_Sucursales_RFCRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Sucursales_RFCResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_ReporteSucursales_RFC", ReplyAction:="*")>  _
        Function Consultar_ReporteSucursales_RFC(ByVal request As WsRemision.Consultar_ReporteSucursales_RFCRequest) As WsRemision.Consultar_ReporteSucursales_RFCResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_ReporteSucursales_RFC", ReplyAction:="*")>  _
        Function Consultar_ReporteSucursales_RFCAsync(ByVal request As WsRemision.Consultar_ReporteSucursales_RFCRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_ReporteSucursales_RFCResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Tickets_Sucursal_ID", ReplyAction:="*")>  _
        Function Consultar_Tickets_Sucursal_ID(ByVal request As WsRemision.Consultar_Tickets_Sucursal_IDRequest) As WsRemision.Consultar_Tickets_Sucursal_IDResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Tickets_Sucursal_ID", ReplyAction:="*")>  _
        Function Consultar_Tickets_Sucursal_IDAsync(ByVal request As WsRemision.Consultar_Tickets_Sucursal_IDRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_Sucursal_IDResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ClaveSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Tickets_Sucursal", ReplyAction:="*")>  _
        Function Consultar_Tickets_Sucursal(ByVal request As WsRemision.Consultar_Tickets_SucursalRequest) As WsRemision.Consultar_Tickets_SucursalResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consultar_Tickets_Sucursal", ReplyAction:="*")>  _
        Function Consultar_Tickets_SucursalAsync(ByVal request As WsRemision.Consultar_Tickets_SucursalRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_SucursalResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ClaveSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Recibir_Ticket_Tecnico", ReplyAction:="*")>  _
        Function Recibir_Ticket_Tecnico(ByVal request As WsRemision.Recibir_Ticket_TecnicoRequest) As WsRemision.Recibir_Ticket_TecnicoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Recibir_Ticket_Tecnico", ReplyAction:="*")>  _
        Function Recibir_Ticket_TecnicoAsync(ByVal request As WsRemision.Recibir_Ticket_TecnicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Recibir_Ticket_TecnicoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ClaveSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Finalizar_Ticket_Tecnico", ReplyAction:="*")>  _
        Function Finalizar_Ticket_Tecnico(ByVal request As WsRemision.Finalizar_Ticket_TecnicoRequest) As WsRemision.Finalizar_Ticket_TecnicoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Finalizar_Ticket_Tecnico", ReplyAction:="*")>  _
        Function Finalizar_Ticket_TecnicoAsync(ByVal request As WsRemision.Finalizar_Ticket_TecnicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Finalizar_Ticket_TecnicoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ClaveSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar_ComentarioTicket_Tenico", ReplyAction:="*")>  _
        Function Agregar_ComentarioTicket_Tenico(ByVal request As WsRemision.Agregar_ComentarioTicket_TenicoRequest) As WsRemision.Agregar_ComentarioTicket_TenicoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar_ComentarioTicket_Tenico", ReplyAction:="*")>  _
        Function Agregar_ComentarioTicket_TenicoAsync(ByVal request As WsRemision.Agregar_ComentarioTicket_TenicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Agregar_ComentarioTicket_TenicoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Deposito_ConsultaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Deposito_Consulta", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Deposito_ConsultaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Deposito_ConsultaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Deposito_ConsultaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Deposito_ConsultaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Deposito_ConsultaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Deposito_ConsultaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Deposito_ConsultaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Deposito_ConsultaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Deposito_ConsultaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Deposito_ConsultaResult As String)
            MyBase.New
            Me.Deposito_ConsultaResult = Deposito_ConsultaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeposRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Depos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.DeposRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.DeposRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeposRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeposResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeposResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.DeposResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.DeposResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeposResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DeposResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DeposResult As String)
            MyBase.New
            Me.DeposResult = DeposResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_puntoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_punto", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Obtener_puntoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Obtener_puntoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Obtener_puntoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_puntoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_puntoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Obtener_puntoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Obtener_puntoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Obtener_puntoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Obtener_puntoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Obtener_puntoResult As String)
            MyBase.New
            Me.Obtener_puntoResult = Obtener_puntoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_RemisionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_Remision", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Obtener_RemisionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Obtener_RemisionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Obtener_RemisionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_RemisionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_RemisionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Obtener_RemisionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Obtener_RemisionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Obtener_RemisionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Obtener_RemisionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Obtener_RemisionResult As String)
            MyBase.New
            Me.Obtener_RemisionResult = Obtener_RemisionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetData", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.SetDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.SetDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetDataResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.SetDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.SetDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SetDataResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetDataResult As String)
            MyBase.New
            Me.SetDataResult = SetDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Guardar_TicketRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Guardar_Ticket", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Guardar_TicketRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Guardar_TicketRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Guardar_TicketRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Guardar_TicketResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Guardar_TicketResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Guardar_TicketResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Guardar_TicketResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Guardar_TicketResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Guardar_TicketResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Guardar_TicketResult As Boolean)
            MyBase.New
            Me.Guardar_TicketResult = Guardar_TicketResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Sucursales_RFCRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Sucursales_RFC", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Sucursales_RFCRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Sucursales_RFCRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Sucursales_RFCRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Sucursales_RFCResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Sucursales_RFCResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Sucursales_RFCResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Sucursales_RFCResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Sucursales_RFCResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Consultar_Sucursales_RFCResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Consultar_Sucursales_RFCResult As String)
            MyBase.New
            Me.Consultar_Sucursales_RFCResult = Consultar_Sucursales_RFCResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_ReporteSucursales_RFCRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_ReporteSucursales_RFC", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_ReporteSucursales_RFCRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_ReporteSucursales_RFCRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_ReporteSucursales_RFCRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_ReporteSucursales_RFCResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_ReporteSucursales_RFCResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_ReporteSucursales_RFCResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_ReporteSucursales_RFCResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_ReporteSucursales_RFCResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Consultar_ReporteSucursales_RFCResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Consultar_ReporteSucursales_RFCResult As String)
            MyBase.New
            Me.Consultar_ReporteSucursales_RFCResult = Consultar_ReporteSucursales_RFCResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Tickets_Sucursal_IDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Tickets_Sucursal_ID", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Tickets_Sucursal_IDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Tickets_Sucursal_IDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Tickets_Sucursal_IDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public parametro As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal parametro As String)
            MyBase.New
            Me.parametro = parametro
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Tickets_Sucursal_IDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Tickets_Sucursal_IDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Tickets_Sucursal_IDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Tickets_Sucursal_IDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Tickets_Sucursal_IDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Consultar_Tickets_Sucursal_IDResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Consultar_Tickets_Sucursal_IDResult As String)
            MyBase.New
            Me.Consultar_Tickets_Sucursal_IDResult = Consultar_Tickets_Sucursal_IDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Tickets_SucursalRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Tickets_Sucursal", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Tickets_SucursalRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Tickets_SucursalRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Tickets_SucursalRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ClaveSucursal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public clave_cliente As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClaveSucursal As String, ByVal clave_cliente As String)
            MyBase.New
            Me.ClaveSucursal = ClaveSucursal
            Me.clave_cliente = clave_cliente
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Consultar_Tickets_SucursalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consultar_Tickets_SucursalResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Consultar_Tickets_SucursalResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Consultar_Tickets_SucursalResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Consultar_Tickets_SucursalResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Consultar_Tickets_SucursalResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Consultar_Tickets_SucursalResult As Object)
            MyBase.New
            Me.Consultar_Tickets_SucursalResult = Consultar_Tickets_SucursalResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Recibir_Ticket_TecnicoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Recibir_Ticket_Tecnico", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Recibir_Ticket_TecnicoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Recibir_Ticket_TecnicoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Recibir_Ticket_TecnicoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ClaveSucursal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Ticket As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClaveSucursal As String, ByVal Ticket As Integer)
            MyBase.New
            Me.ClaveSucursal = ClaveSucursal
            Me.Ticket = Ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Recibir_Ticket_TecnicoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Recibir_Ticket_TecnicoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Recibir_Ticket_TecnicoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Recibir_Ticket_TecnicoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Recibir_Ticket_TecnicoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Recibir_Ticket_TecnicoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Recibir_Ticket_TecnicoResult As Boolean)
            MyBase.New
            Me.Recibir_Ticket_TecnicoResult = Recibir_Ticket_TecnicoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Finalizar_Ticket_TecnicoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Finalizar_Ticket_Tecnico", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Finalizar_Ticket_TecnicoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Finalizar_Ticket_TecnicoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Finalizar_Ticket_TecnicoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ClaveSucursal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ticket As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClaveSucursal As String, ByVal ticket As Integer)
            MyBase.New
            Me.ClaveSucursal = ClaveSucursal
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Finalizar_Ticket_TecnicoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Finalizar_Ticket_TecnicoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Finalizar_Ticket_TecnicoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Finalizar_Ticket_TecnicoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Finalizar_Ticket_TecnicoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Finalizar_Ticket_TecnicoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Finalizar_Ticket_TecnicoResult As Boolean)
            MyBase.New
            Me.Finalizar_Ticket_TecnicoResult = Finalizar_Ticket_TecnicoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Agregar_ComentarioTicket_TenicoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Agregar_ComentarioTicket_Tenico", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Agregar_ComentarioTicket_TenicoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Agregar_ComentarioTicket_TenicoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Agregar_ComentarioTicket_TenicoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ClaveSucursal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ticket As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public comentario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClaveSucursal As String, ByVal ticket As Integer, ByVal comentario As String)
            MyBase.New
            Me.ClaveSucursal = ClaveSucursal
            Me.ticket = ticket
            Me.comentario = comentario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Agregar_ComentarioTicket_TenicoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Agregar_ComentarioTicket_TenicoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsRemision.Agregar_ComentarioTicket_TenicoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsRemision.Agregar_ComentarioTicket_TenicoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Agregar_ComentarioTicket_TenicoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Agregar_ComentarioTicket_TenicoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Agregar_ComentarioTicket_TenicoResult As Boolean)
            MyBase.New
            Me.Agregar_ComentarioTicket_TenicoResult = Agregar_ComentarioTicket_TenicoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WsCashFlowSoapChannel
        Inherits WsRemision.WsCashFlowSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WsCashFlowSoapClient
        Inherits System.ServiceModel.ClientBase(Of WsRemision.WsCashFlowSoap)
        Implements WsRemision.WsCashFlowSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Deposito_Consulta(ByVal request As WsRemision.Deposito_ConsultaRequest) As WsRemision.Deposito_ConsultaResponse Implements WsRemision.WsCashFlowSoap.Deposito_Consulta
            Return MyBase.Channel.Deposito_Consulta(request)
        End Function
        
        Public Function Deposito_Consulta(ByVal parametro As String) As String
            Dim inValue As WsRemision.Deposito_ConsultaRequest = New WsRemision.Deposito_ConsultaRequest()
            inValue.Body = New WsRemision.Deposito_ConsultaRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Deposito_ConsultaResponse = CType(Me,WsRemision.WsCashFlowSoap).Deposito_Consulta(inValue)
            Return retVal.Body.Deposito_ConsultaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Deposito_ConsultaAsync(ByVal request As WsRemision.Deposito_ConsultaRequest) As System.Threading.Tasks.Task(Of WsRemision.Deposito_ConsultaResponse) Implements WsRemision.WsCashFlowSoap.Deposito_ConsultaAsync
            Return MyBase.Channel.Deposito_ConsultaAsync(request)
        End Function
        
        Public Function Deposito_ConsultaAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Deposito_ConsultaResponse)
            Dim inValue As WsRemision.Deposito_ConsultaRequest = New WsRemision.Deposito_ConsultaRequest()
            inValue.Body = New WsRemision.Deposito_ConsultaRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Deposito_ConsultaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Depos(ByVal request As WsRemision.DeposRequest) As WsRemision.DeposResponse Implements WsRemision.WsCashFlowSoap.Depos
            Return MyBase.Channel.Depos(request)
        End Function
        
        Public Function Depos(ByVal parametro As String) As String
            Dim inValue As WsRemision.DeposRequest = New WsRemision.DeposRequest()
            inValue.Body = New WsRemision.DeposRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.DeposResponse = CType(Me,WsRemision.WsCashFlowSoap).Depos(inValue)
            Return retVal.Body.DeposResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_DeposAsync(ByVal request As WsRemision.DeposRequest) As System.Threading.Tasks.Task(Of WsRemision.DeposResponse) Implements WsRemision.WsCashFlowSoap.DeposAsync
            Return MyBase.Channel.DeposAsync(request)
        End Function
        
        Public Function DeposAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.DeposResponse)
            Dim inValue As WsRemision.DeposRequest = New WsRemision.DeposRequest()
            inValue.Body = New WsRemision.DeposRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).DeposAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Obtener_punto(ByVal request As WsRemision.Obtener_puntoRequest) As WsRemision.Obtener_puntoResponse Implements WsRemision.WsCashFlowSoap.Obtener_punto
            Return MyBase.Channel.Obtener_punto(request)
        End Function
        
        Public Function Obtener_punto(ByVal parametro As String) As String
            Dim inValue As WsRemision.Obtener_puntoRequest = New WsRemision.Obtener_puntoRequest()
            inValue.Body = New WsRemision.Obtener_puntoRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Obtener_puntoResponse = CType(Me,WsRemision.WsCashFlowSoap).Obtener_punto(inValue)
            Return retVal.Body.Obtener_puntoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Obtener_puntoAsync(ByVal request As WsRemision.Obtener_puntoRequest) As System.Threading.Tasks.Task(Of WsRemision.Obtener_puntoResponse) Implements WsRemision.WsCashFlowSoap.Obtener_puntoAsync
            Return MyBase.Channel.Obtener_puntoAsync(request)
        End Function
        
        Public Function Obtener_puntoAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Obtener_puntoResponse)
            Dim inValue As WsRemision.Obtener_puntoRequest = New WsRemision.Obtener_puntoRequest()
            inValue.Body = New WsRemision.Obtener_puntoRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Obtener_puntoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Obtener_Remision(ByVal request As WsRemision.Obtener_RemisionRequest) As WsRemision.Obtener_RemisionResponse Implements WsRemision.WsCashFlowSoap.Obtener_Remision
            Return MyBase.Channel.Obtener_Remision(request)
        End Function
        
        Public Function Obtener_Remision(ByVal parametro As String) As String
            Dim inValue As WsRemision.Obtener_RemisionRequest = New WsRemision.Obtener_RemisionRequest()
            inValue.Body = New WsRemision.Obtener_RemisionRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Obtener_RemisionResponse = CType(Me,WsRemision.WsCashFlowSoap).Obtener_Remision(inValue)
            Return retVal.Body.Obtener_RemisionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Obtener_RemisionAsync(ByVal request As WsRemision.Obtener_RemisionRequest) As System.Threading.Tasks.Task(Of WsRemision.Obtener_RemisionResponse) Implements WsRemision.WsCashFlowSoap.Obtener_RemisionAsync
            Return MyBase.Channel.Obtener_RemisionAsync(request)
        End Function
        
        Public Function Obtener_RemisionAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Obtener_RemisionResponse)
            Dim inValue As WsRemision.Obtener_RemisionRequest = New WsRemision.Obtener_RemisionRequest()
            inValue.Body = New WsRemision.Obtener_RemisionRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Obtener_RemisionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_SetData(ByVal request As WsRemision.SetDataRequest) As WsRemision.SetDataResponse Implements WsRemision.WsCashFlowSoap.SetData
            Return MyBase.Channel.SetData(request)
        End Function
        
        Public Function SetData(ByVal parametro As String) As String
            Dim inValue As WsRemision.SetDataRequest = New WsRemision.SetDataRequest()
            inValue.Body = New WsRemision.SetDataRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.SetDataResponse = CType(Me,WsRemision.WsCashFlowSoap).SetData(inValue)
            Return retVal.Body.SetDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_SetDataAsync(ByVal request As WsRemision.SetDataRequest) As System.Threading.Tasks.Task(Of WsRemision.SetDataResponse) Implements WsRemision.WsCashFlowSoap.SetDataAsync
            Return MyBase.Channel.SetDataAsync(request)
        End Function
        
        Public Function SetDataAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.SetDataResponse)
            Dim inValue As WsRemision.SetDataRequest = New WsRemision.SetDataRequest()
            inValue.Body = New WsRemision.SetDataRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).SetDataAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Guardar_Ticket(ByVal request As WsRemision.Guardar_TicketRequest) As WsRemision.Guardar_TicketResponse Implements WsRemision.WsCashFlowSoap.Guardar_Ticket
            Return MyBase.Channel.Guardar_Ticket(request)
        End Function
        
        Public Function Guardar_Ticket(ByVal parametro As String) As Boolean
            Dim inValue As WsRemision.Guardar_TicketRequest = New WsRemision.Guardar_TicketRequest()
            inValue.Body = New WsRemision.Guardar_TicketRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Guardar_TicketResponse = CType(Me,WsRemision.WsCashFlowSoap).Guardar_Ticket(inValue)
            Return retVal.Body.Guardar_TicketResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Guardar_TicketAsync(ByVal request As WsRemision.Guardar_TicketRequest) As System.Threading.Tasks.Task(Of WsRemision.Guardar_TicketResponse) Implements WsRemision.WsCashFlowSoap.Guardar_TicketAsync
            Return MyBase.Channel.Guardar_TicketAsync(request)
        End Function
        
        Public Function Guardar_TicketAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Guardar_TicketResponse)
            Dim inValue As WsRemision.Guardar_TicketRequest = New WsRemision.Guardar_TicketRequest()
            inValue.Body = New WsRemision.Guardar_TicketRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Guardar_TicketAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Sucursales_RFC(ByVal request As WsRemision.Consultar_Sucursales_RFCRequest) As WsRemision.Consultar_Sucursales_RFCResponse Implements WsRemision.WsCashFlowSoap.Consultar_Sucursales_RFC
            Return MyBase.Channel.Consultar_Sucursales_RFC(request)
        End Function
        
        Public Function Consultar_Sucursales_RFC(ByVal parametro As String) As String
            Dim inValue As WsRemision.Consultar_Sucursales_RFCRequest = New WsRemision.Consultar_Sucursales_RFCRequest()
            inValue.Body = New WsRemision.Consultar_Sucursales_RFCRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Consultar_Sucursales_RFCResponse = CType(Me,WsRemision.WsCashFlowSoap).Consultar_Sucursales_RFC(inValue)
            Return retVal.Body.Consultar_Sucursales_RFCResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Sucursales_RFCAsync(ByVal request As WsRemision.Consultar_Sucursales_RFCRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Sucursales_RFCResponse) Implements WsRemision.WsCashFlowSoap.Consultar_Sucursales_RFCAsync
            Return MyBase.Channel.Consultar_Sucursales_RFCAsync(request)
        End Function
        
        Public Function Consultar_Sucursales_RFCAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Sucursales_RFCResponse)
            Dim inValue As WsRemision.Consultar_Sucursales_RFCRequest = New WsRemision.Consultar_Sucursales_RFCRequest()
            inValue.Body = New WsRemision.Consultar_Sucursales_RFCRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Consultar_Sucursales_RFCAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_ReporteSucursales_RFC(ByVal request As WsRemision.Consultar_ReporteSucursales_RFCRequest) As WsRemision.Consultar_ReporteSucursales_RFCResponse Implements WsRemision.WsCashFlowSoap.Consultar_ReporteSucursales_RFC
            Return MyBase.Channel.Consultar_ReporteSucursales_RFC(request)
        End Function
        
        Public Function Consultar_ReporteSucursales_RFC(ByVal parametro As String) As String
            Dim inValue As WsRemision.Consultar_ReporteSucursales_RFCRequest = New WsRemision.Consultar_ReporteSucursales_RFCRequest()
            inValue.Body = New WsRemision.Consultar_ReporteSucursales_RFCRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Consultar_ReporteSucursales_RFCResponse = CType(Me,WsRemision.WsCashFlowSoap).Consultar_ReporteSucursales_RFC(inValue)
            Return retVal.Body.Consultar_ReporteSucursales_RFCResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_ReporteSucursales_RFCAsync(ByVal request As WsRemision.Consultar_ReporteSucursales_RFCRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_ReporteSucursales_RFCResponse) Implements WsRemision.WsCashFlowSoap.Consultar_ReporteSucursales_RFCAsync
            Return MyBase.Channel.Consultar_ReporteSucursales_RFCAsync(request)
        End Function
        
        Public Function Consultar_ReporteSucursales_RFCAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Consultar_ReporteSucursales_RFCResponse)
            Dim inValue As WsRemision.Consultar_ReporteSucursales_RFCRequest = New WsRemision.Consultar_ReporteSucursales_RFCRequest()
            inValue.Body = New WsRemision.Consultar_ReporteSucursales_RFCRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Consultar_ReporteSucursales_RFCAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Tickets_Sucursal_ID(ByVal request As WsRemision.Consultar_Tickets_Sucursal_IDRequest) As WsRemision.Consultar_Tickets_Sucursal_IDResponse Implements WsRemision.WsCashFlowSoap.Consultar_Tickets_Sucursal_ID
            Return MyBase.Channel.Consultar_Tickets_Sucursal_ID(request)
        End Function
        
        Public Function Consultar_Tickets_Sucursal_ID(ByVal parametro As String) As String
            Dim inValue As WsRemision.Consultar_Tickets_Sucursal_IDRequest = New WsRemision.Consultar_Tickets_Sucursal_IDRequest()
            inValue.Body = New WsRemision.Consultar_Tickets_Sucursal_IDRequestBody()
            inValue.Body.parametro = parametro
            Dim retVal As WsRemision.Consultar_Tickets_Sucursal_IDResponse = CType(Me,WsRemision.WsCashFlowSoap).Consultar_Tickets_Sucursal_ID(inValue)
            Return retVal.Body.Consultar_Tickets_Sucursal_IDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Tickets_Sucursal_IDAsync(ByVal request As WsRemision.Consultar_Tickets_Sucursal_IDRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_Sucursal_IDResponse) Implements WsRemision.WsCashFlowSoap.Consultar_Tickets_Sucursal_IDAsync
            Return MyBase.Channel.Consultar_Tickets_Sucursal_IDAsync(request)
        End Function
        
        Public Function Consultar_Tickets_Sucursal_IDAsync(ByVal parametro As String) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_Sucursal_IDResponse)
            Dim inValue As WsRemision.Consultar_Tickets_Sucursal_IDRequest = New WsRemision.Consultar_Tickets_Sucursal_IDRequest()
            inValue.Body = New WsRemision.Consultar_Tickets_Sucursal_IDRequestBody()
            inValue.Body.parametro = parametro
            Return CType(Me,WsRemision.WsCashFlowSoap).Consultar_Tickets_Sucursal_IDAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Tickets_Sucursal(ByVal request As WsRemision.Consultar_Tickets_SucursalRequest) As WsRemision.Consultar_Tickets_SucursalResponse Implements WsRemision.WsCashFlowSoap.Consultar_Tickets_Sucursal
            Return MyBase.Channel.Consultar_Tickets_Sucursal(request)
        End Function
        
        Public Function Consultar_Tickets_Sucursal(ByVal ClaveSucursal As String, ByVal clave_cliente As String) As Object
            Dim inValue As WsRemision.Consultar_Tickets_SucursalRequest = New WsRemision.Consultar_Tickets_SucursalRequest()
            inValue.Body = New WsRemision.Consultar_Tickets_SucursalRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.clave_cliente = clave_cliente
            Dim retVal As WsRemision.Consultar_Tickets_SucursalResponse = CType(Me,WsRemision.WsCashFlowSoap).Consultar_Tickets_Sucursal(inValue)
            Return retVal.Body.Consultar_Tickets_SucursalResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Consultar_Tickets_SucursalAsync(ByVal request As WsRemision.Consultar_Tickets_SucursalRequest) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_SucursalResponse) Implements WsRemision.WsCashFlowSoap.Consultar_Tickets_SucursalAsync
            Return MyBase.Channel.Consultar_Tickets_SucursalAsync(request)
        End Function
        
        Public Function Consultar_Tickets_SucursalAsync(ByVal ClaveSucursal As String, ByVal clave_cliente As String) As System.Threading.Tasks.Task(Of WsRemision.Consultar_Tickets_SucursalResponse)
            Dim inValue As WsRemision.Consultar_Tickets_SucursalRequest = New WsRemision.Consultar_Tickets_SucursalRequest()
            inValue.Body = New WsRemision.Consultar_Tickets_SucursalRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.clave_cliente = clave_cliente
            Return CType(Me,WsRemision.WsCashFlowSoap).Consultar_Tickets_SucursalAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Recibir_Ticket_Tecnico(ByVal request As WsRemision.Recibir_Ticket_TecnicoRequest) As WsRemision.Recibir_Ticket_TecnicoResponse Implements WsRemision.WsCashFlowSoap.Recibir_Ticket_Tecnico
            Return MyBase.Channel.Recibir_Ticket_Tecnico(request)
        End Function
        
        Public Function Recibir_Ticket_Tecnico(ByVal ClaveSucursal As String, ByVal Ticket As Integer) As Boolean
            Dim inValue As WsRemision.Recibir_Ticket_TecnicoRequest = New WsRemision.Recibir_Ticket_TecnicoRequest()
            inValue.Body = New WsRemision.Recibir_Ticket_TecnicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.Ticket = Ticket
            Dim retVal As WsRemision.Recibir_Ticket_TecnicoResponse = CType(Me,WsRemision.WsCashFlowSoap).Recibir_Ticket_Tecnico(inValue)
            Return retVal.Body.Recibir_Ticket_TecnicoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Recibir_Ticket_TecnicoAsync(ByVal request As WsRemision.Recibir_Ticket_TecnicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Recibir_Ticket_TecnicoResponse) Implements WsRemision.WsCashFlowSoap.Recibir_Ticket_TecnicoAsync
            Return MyBase.Channel.Recibir_Ticket_TecnicoAsync(request)
        End Function
        
        Public Function Recibir_Ticket_TecnicoAsync(ByVal ClaveSucursal As String, ByVal Ticket As Integer) As System.Threading.Tasks.Task(Of WsRemision.Recibir_Ticket_TecnicoResponse)
            Dim inValue As WsRemision.Recibir_Ticket_TecnicoRequest = New WsRemision.Recibir_Ticket_TecnicoRequest()
            inValue.Body = New WsRemision.Recibir_Ticket_TecnicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.Ticket = Ticket
            Return CType(Me,WsRemision.WsCashFlowSoap).Recibir_Ticket_TecnicoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Finalizar_Ticket_Tecnico(ByVal request As WsRemision.Finalizar_Ticket_TecnicoRequest) As WsRemision.Finalizar_Ticket_TecnicoResponse Implements WsRemision.WsCashFlowSoap.Finalizar_Ticket_Tecnico
            Return MyBase.Channel.Finalizar_Ticket_Tecnico(request)
        End Function
        
        Public Function Finalizar_Ticket_Tecnico(ByVal ClaveSucursal As String, ByVal ticket As Integer) As Boolean
            Dim inValue As WsRemision.Finalizar_Ticket_TecnicoRequest = New WsRemision.Finalizar_Ticket_TecnicoRequest()
            inValue.Body = New WsRemision.Finalizar_Ticket_TecnicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.ticket = ticket
            Dim retVal As WsRemision.Finalizar_Ticket_TecnicoResponse = CType(Me,WsRemision.WsCashFlowSoap).Finalizar_Ticket_Tecnico(inValue)
            Return retVal.Body.Finalizar_Ticket_TecnicoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Finalizar_Ticket_TecnicoAsync(ByVal request As WsRemision.Finalizar_Ticket_TecnicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Finalizar_Ticket_TecnicoResponse) Implements WsRemision.WsCashFlowSoap.Finalizar_Ticket_TecnicoAsync
            Return MyBase.Channel.Finalizar_Ticket_TecnicoAsync(request)
        End Function
        
        Public Function Finalizar_Ticket_TecnicoAsync(ByVal ClaveSucursal As String, ByVal ticket As Integer) As System.Threading.Tasks.Task(Of WsRemision.Finalizar_Ticket_TecnicoResponse)
            Dim inValue As WsRemision.Finalizar_Ticket_TecnicoRequest = New WsRemision.Finalizar_Ticket_TecnicoRequest()
            inValue.Body = New WsRemision.Finalizar_Ticket_TecnicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.ticket = ticket
            Return CType(Me,WsRemision.WsCashFlowSoap).Finalizar_Ticket_TecnicoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Agregar_ComentarioTicket_Tenico(ByVal request As WsRemision.Agregar_ComentarioTicket_TenicoRequest) As WsRemision.Agregar_ComentarioTicket_TenicoResponse Implements WsRemision.WsCashFlowSoap.Agregar_ComentarioTicket_Tenico
            Return MyBase.Channel.Agregar_ComentarioTicket_Tenico(request)
        End Function
        
        Public Function Agregar_ComentarioTicket_Tenico(ByVal ClaveSucursal As String, ByVal ticket As Integer, ByVal comentario As String) As Boolean
            Dim inValue As WsRemision.Agregar_ComentarioTicket_TenicoRequest = New WsRemision.Agregar_ComentarioTicket_TenicoRequest()
            inValue.Body = New WsRemision.Agregar_ComentarioTicket_TenicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.ticket = ticket
            inValue.Body.comentario = comentario
            Dim retVal As WsRemision.Agregar_ComentarioTicket_TenicoResponse = CType(Me,WsRemision.WsCashFlowSoap).Agregar_ComentarioTicket_Tenico(inValue)
            Return retVal.Body.Agregar_ComentarioTicket_TenicoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRemision_WsCashFlowSoap_Agregar_ComentarioTicket_TenicoAsync(ByVal request As WsRemision.Agregar_ComentarioTicket_TenicoRequest) As System.Threading.Tasks.Task(Of WsRemision.Agregar_ComentarioTicket_TenicoResponse) Implements WsRemision.WsCashFlowSoap.Agregar_ComentarioTicket_TenicoAsync
            Return MyBase.Channel.Agregar_ComentarioTicket_TenicoAsync(request)
        End Function
        
        Public Function Agregar_ComentarioTicket_TenicoAsync(ByVal ClaveSucursal As String, ByVal ticket As Integer, ByVal comentario As String) As System.Threading.Tasks.Task(Of WsRemision.Agregar_ComentarioTicket_TenicoResponse)
            Dim inValue As WsRemision.Agregar_ComentarioTicket_TenicoRequest = New WsRemision.Agregar_ComentarioTicket_TenicoRequest()
            inValue.Body = New WsRemision.Agregar_ComentarioTicket_TenicoRequestBody()
            inValue.Body.ClaveSucursal = ClaveSucursal
            inValue.Body.ticket = ticket
            inValue.Body.comentario = comentario
            Return CType(Me,WsRemision.WsCashFlowSoap).Agregar_ComentarioTicket_TenicoAsync(inValue)
        End Function
    End Class
End Namespace
